---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-added-large-files
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: fix-encoding-pragma
        args: [--remove]
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.5.1
    hooks:
      - id: check-pre-commit-ci-config
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.18.1
    hooks:
      - id: validate_manifest
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
      - id: reorder-python-imports
        exclude: ^(before_commit/resources/|testing/resources/python3_hooks_repo/|before_commit/__init__.py)
        args: [--py37-plus, --add-import, 'from __future__ import annotations']
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args:
          - --ignore-missing-imports
          - --scripts-are-modules
          - --no-warn-unused-ignores
          - --show-error-codes
        exclude: ^testing/resources/
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.14.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        args:
          - "--exclude=1091"
